module.exports = {
    'dashboard.js': 'a',
    'reserve.js': 'b',
    'goods.js': 'c',
    'order.js': 'd',
    'scrm.js': 'e',
    'report.js': 'f',
    'asset.js': 'g',
    'marketing.js': 'h',
    'store.js': 'i',
    'setting.js': 'j',
    'bill.js': 'k',
    'cashier.js': 'l',
    'preview.js': 'm',
    'team.js': 'n',
}